### ISSUE TITLE
As a student planning for my modules, I want to be able to select from a various number of timetable slots for each of my modules. It would be even better if the software is able to suggest an optimum schedule for me.  

### ISSUE THREAD

**Issue by tuandingwei** [AY1920S1-CS2103-T16-2/main#14]

**Comment by victorvic54** [comment]
Since we need to refrain from user clicking rather that user input, I think we need to brainstorm about how we can do this.

**Comment by tuandingwei** [comment]
Maybe, since tutorial and lecture slots are number we can get them to select the slots they want by indicating the lecture/ tutorial slot.
